name: github action CI/CD í…ŒìŠ¤íŠ¸ìš©
on:
  pull_request:
    branches:
      - develop
      - master
    paths: "frontend/*"

defaults:
  run:
    working-directory: frontend

jobs:
  deployment:
    name: Deployment-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setting node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          
      - name: npm install & build
        run: |
          npm install
          npm run build

      - name: Deploy to github pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './frontend/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Format comment message
        id: format_comment_message
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
          
            const deployURL = 'https://usageness.github.io/gitflow-test/';
            const comments = [
              `## Deploy Preview`,
              `ðŸ”¥ **check your project preview here!** : `
            ].join('\n');
            
            core.setOutput('comment', comments);
            
      - name: comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          message: |
            ${{ steps.format_comment_message.outputs.comment}}[${{ steps.deployment.outputs.page_url }}](${{ steps.deployment.outputs.page_url }})
